CREATE TABLE USERS (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    pass VARCHAR(255) NOT NULL
);

CREATE TABLE PROFILES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    bio VARCHAR(255),
    user_id INT,
    FOREIGN KEY (user_id) REFERENCES USERS(id)
);
START TRANSACTION

